In [1]:
import pandas as pd
import numpy as np

In [8]:
dataset = pd.read_csv('https://raw.githubusercontent.com/afrozchakure/Internity-Summer-Internship-Work/master/Blogs/Preprocessing/Data.csv')

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [11]:
x = dataset.iloc[:,:-1].values #independent
y = dataset.iloc[:,3].values  #dependent

print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [12]:
from sklearn.preprocessing import LabelEncoder
country = LabelEncoder()
x[:,0] = country.fit_transform(x[:,0])
print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 nan]
 [0 35.0 58000.0]
 [2 nan 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [15]:
#encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columnTransformer = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(columnTransformer.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
#handling missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")

imputer.fit(x[:,1:3])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [17]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [18]:
#spliting data into training set and testing set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()

x_train = scx.fit_transform(x_train)
x_test = scx.transform(x_test)

In [21]:
print(x_train)

[[-1.          2.64575131 -0.77459667  0.25315802         nan]
 [ 1.         -0.37796447 -0.77459667 -0.23014365  0.44897083]
 [-1.         -0.37796447  1.29099445 -1.84114924 -1.41706417]
 [-1.         -0.37796447  1.29099445         nan -1.0242147 ]
 [ 1.         -0.37796447 -0.77459667  1.54196248  1.62751925]
 [-1.         -0.37796447  1.29099445 -0.0690431  -0.14030338]
 [ 1.         -0.37796447 -0.77459667  0.89756025  0.94003267]
 [ 1.         -0.37796447 -0.77459667 -0.55234477 -0.43494049]]


In [22]:
print(x_test)

[[-1.          2.64575131 -0.77459667 -1.35784756 -0.82778996]
 [-1.          2.64575131 -0.77459667  1.8641636   2.02036872]]
